services:
  mysql:
    image: mysql 
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    ports:
      - 3306:3306 
    platform: "linux"
  redis:
    image: redis
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
    environment:
      appendonly: yes
      privileged: true
    command: 
      redis-server --port 6379 --requirepass 123456  --appendonly yes
    platform: "linux"
  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    platform: "linux"
  nacos:
    image: nacos/nacos-server
    restart: always
    ports:
      - "8848:8848"
    environment:
      MODE: standalone
    platform: "linux"