services:
  mysql:
    image: mysql 
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    ports:
      - 3306:3306 
    platform: "linux/arm64/v8"
  redis:
    image: redis
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
    environment:
      appendonly: yes
      privileged: true
    command: 
      redis-server --port 6379 --requirepass 123456  --appendonly yes
    platform: "linux/arm64/v8"
  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    platform: "linux/arm64/v8"
  nacos:
    image: alvarowen/nacos:m1-2.0.3
    restart: always
    ports:
      - "8848:8848"
    environment:
      MODE: standalone
    platform: "linux/arm64"
  chatgpt:
    image: pengzhile/pandora
    restart: always
    ports:
      - "3000:3000"
    environment:
      PANDORA_CLOUD: cloud
      PANDORA_SERVER: 0.0.0.0:3000
    platform: "linux/arm64"